---

- name: Uninstall (container_mode fact)
  ansible.builtin.set_fact:
    container_mode: "Uninstall"

- name: "{{ container_mode }} | services"
  ansible.builtin.include_tasks: services.yml

- name: "{{ container_mode }} | files"
  ansible.builtin.include_tasks: files.yml

- name: "{{ container_mode }} | directories"
  ansible.builtin.include_tasks: directories.yml

- name: "{{ container_mode }} | systems"
  when: systems_managed
  ansible.builtin.include_tasks: systems.yml

- name: "{{ container_mode }} | users"
  when: users_managed
  ansible.builtin.include_tasks: users.yml

- name: "{{ container_mode }} | packages"
  when: packages_managed
  ansible.builtin.include_tasks: packages.yml
