---

updates_version: "latest"

container_templates:
  - src: "nginx.default.conf.j2"
    dest: "{{ container_pod_etc_dir }}/nginx.default.conf"
    owner: "{{ container_user_owner }}"
    group: "{{ container_user_group_service }}"

container_pod_containers:
  - name: container_name_a
    image_name: docker.io/nginx
    image_tag: "{{ updates_version }}"
    description: Web host A
    ports:
      - containerPort: 88
        hostPort: 8088
        protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: "256M"
    volumeMounts:
      - mountPath: /etc/nginx/conf.d/default.conf:ro,z
        name: nginx-default-conf

container_pod_volumes:
  - name: nginx-default-conf
    hostPath:
      path: "{{ container_pod_etc_dir }}/nginx.default.conf"
