---

container_pod_labels:
  app: "Verify label {{ container_pod_name }}"

updates_version: "1.22.1"

container_pod_containers:
  - name: container_name_a
    image_name: docker.io/nginx
    image_tag: "{{ updates_version }}"
    description: Web host A
    ports:
      - containerPort: 88
        hostPort: 8088
        protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: "256M"
    volumeMounts:
      - mountPath: /etc/nginx/conf.d/default.conf:ro,z
        name: nginx-default-conf
