---

user_groups:
  - name: container_user_group
  - name: container_user_group_service
  - name: container_user_group_logs
  - name: container_user_group_access_logs
user_users:
  - name: container_user_owner
    group: container_user_group
    create_home: true
  - name: container_user_owner_service
    group: container_user_group_service
    create_home: true
    groups: container_user_group_logs
  - name: container_user_access_logs
    group: container_user_group_access_logs
    groups: container_user_group_logs

package_packages:
  - {package: systemd-container}
  - {package: acl}
  - {package: iptables-nft}
  - {package: podman}

container_run_as_user_owner: 999

nginx_pod_etc_dir: "{{ container_pod_home_dir }}/etc"
nginx_pod_logs_dir: "{{ container_pod_home_dir }}/logs"

# Manage container
container_directories:
  - path: "{{ container_pod_home_dir }}/molecule-directory-test-to-delete"
    owner: "{{ container_user_owner }}"
    group: "{{ container_user_group_service }}"
    mode: "{{ container_directories_mode }}"
  - path: "{{ nginx_pod_etc_dir }}"
    group: "{{ container_user_group_service }}"
  - path: "{{ nginx_pod_logs_dir }}"
    unshare: true

container_templates:
  - src: "nginx.default.conf.j2"
    dest: "{{ nginx_pod_etc_dir }}/nginx.default.conf"
    owner: "{{ container_user_owner }}"
    group: "{{ container_user_group_service }}"
    mode: "{{ container_files_mode }}"
    setype: container_file_t

container_files:
  - src: "molecule-file-test-to-delete"
    dest: "{{ container_pod_home_dir }}/molecule-directory-test-to-delete/molecule-file-test-to-delete"
    owner: "{{ container_user_owner }}"
    group: "{{ container_user_group_service }}"
    mode: "{{ container_files_mode }}"
    setype: container_file_t
    unshare: true

updates_version: "latest"

container_pod_containers:
  - name: container_name_a
    image_name: docker.io/nginx
    image_tag: "{{ updates_version }}"
    description: Web host A
    ports:
      - containerPort: 88
        hostPort: 8088
        protocol: TCP
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    volumeMounts:
      - mountPath: /etc/nginx/conf.d/default.conf:ro,z
        name: nginx-default-conf
      - mountPath: /var/log/nginx:rw,z
        name: nginx-logs

container_pod_volumes:
  - name: nginx-default-conf
    hostPath:
      path: "{{ nginx_pod_etc_dir }}/nginx.default.conf"
  - name: nginx-logs
    hostPath:
      path: "{{ nginx_pod_logs_dir }}"

#container_registries:
#  - username: "docker_user_registry"
#    password: "docker_user_password_registry"
#    url: "docker.io"
