---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/collections.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
platforms:
  - name: molecule-container-role-instance-1-fedora37
    box: "fedora/37-cloud-base"
    box_version: "37.20221105.0"
    memory: 4096
    cpus: 2
    timezone: Europe/Zurich
    groups:
      - container
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      timeout: 30
verifier:
  name: ansible
