name: MOLECULE TEST

'on':
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    uses: .github/workflows/molecule-lint.yml@main

  test:
    needs: lint
    uses: buissetemmanuel/cicd-templates/.github/workflows/molecule-test.yml@main
    strategy:
      matrix:
        distro:
          - fedora37
